version: '3.8'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - db-data:/data
    environment:
      - TYPEORM_CONNECTION=sqlite
      - TYPEORM_DATABASE=./data/db.sqlite
volumes:
  db-data: